sudo: required
language: python
dist: xenial
python:
- '3.7'

install:
  - python --version
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -e .
  - sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386

script:
  - cd tests && ./run_tests

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "u0Uvw3BrvDe9ymWhtdq436naawF6J0FB30G2d2Gx2WKJ7UU9JXNeVnvlin+V5rXIRO2IT7xV4jeUFm64jSfr33UtajBMFWJhK8pygtMWWcuFMHu46U3xhnWPo6TisYI+ySZ+CVy0ycdusfQfbI4O7he87W/IRNFb2Zj6NjZuVI3x6MIG4e3PxReYq0YH1mJ16hKtT6FQxnwNuWqG9jk9ZBAlL0xWsTgZRbOwiZGeCs7jdqSXkzu4zCxtV1ZJAbTWja+FI6GVM33m7qZLKUpLIxkszWvAssgjx88eb6v+GVl+CyStOCE1xvULs+CBVRg4Q9TfWWcbiKQRPAWk67vAQ42CNiTOO1U+Iw58Erx12AmFpBeXfgbSTHed//+ZyN/YE/h9St1gSNc1eUsQAQkCWnbQByK8ic+b/UmPGV4UFUh00XzJSMAWNPeuQnrMhGK63BSaFC9M1erwIksvhzxmqgiUq5nT3UK7PebMHVcpU81TY7ZAht75r+x0Ml8phx0paMxOdFg5FSRRcD+Cv+amt2bETWKh0CMLAIZFAWH5AuRhwbvnK0eSktbro2ZmfzBWWansXIMllG56j9maBq6+UZXgkxhTJUSD7vnVdN0NtgxYVzSNfgUQyBfZ0HrgqjH2He0zQzDXhA9JAgZ6kvAiIkDJxJZMM/hV5xKdIOYXthE="
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION = 3.7"
  distributions: "sdist bdist_wheel"
  skip_existing: true
