sudo: required
language: python
dist: xenial
python:
- '3.7'

install:
  - python --version
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - pip install -e .
  - sudo apt-get install libc6:i386 libncurses5:i386 libstdc++6:i386

script:
  - cd tests && ./run_tests

deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: "JUsC1l4TuW4LWarP6Axe02YWbXpKYHhgDqGilSay3D2OgYrtEetzimfXGgsNj2TjZZNHkC6vYoKIEq91NrgNRO3wgTPiCsfOTKtDSnCUcX4eFUoZ0wX1HJG82s83hWqqTDRMB+GmXNl94eNpcXrk0nblBdzhai0T/KoftNqI8TPg19qkhE7PftBF8lpRdiU4W51UYA7PyB9VgCN++2bAzQaEwKmOo6HOMX33XHual/gcrKIy7V19ax0FmfaIR4iYF+MqysWoNve8a+GxAbYDoY88TlOja5I4l7ipdpxo/Aik+5vgp/6e/QzcW2C5f8LFCtyTPk0rQhgnAXFko+g5XKIacoFqLRZUqUww/ZZDbDA1Op0g1ue3yNpwY8iwhbQZtA/uXG0KaMkbQN8ihB8y3/Q0APkHA8H+AqOAJdP8cwcPf25axP/67XBmoJLyLEz3rRxPFZFfawDXEXArCmHVehLYneOZKLD1Dhgv4NFSZ3qajPZp4tfofnR042XxOmcSOC9BWDGKS38oAN1RBTUAG2dYZqtLZMBY8ak7smhuIGbsBG+HhHCHVaV8+bpX4XSUncH+UW0KCKhKmLugId3blavW5AYN94Zibv53efUoSsQZ6RtY1Fxo5dGbHv2hHj3ZCtr4gf387/31L/6rX1292j9qzZMZ+WiD+AhqXHiGmtc="
  on:
    tags: true
    condition: "$TRAVIS_PYTHON_VERSION = 3.7"
  distributions: "sdist bdist_wheel"
  skip_existing: true
